version: "2"
services:
 couchbase-server:
   build: ./couchbase-server
   ports:
    - 8091-8096:8091-8096
    - 11210:11210
   environment:  
     - CLUSTER_NAME=couchbase-demo
     - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
     - COUCHBASE_ADMINISTRATOR_PASSWORD=password
     - COUCHBASE_BUCKET=projects
     - COUCHBASE_BUCKET_RAMSIZE=512
     - COUCHBASE_RBAC_USERNAME=admin
     - COUCHBASE_RBAC_PASSWORD=P@$$w0rd
     - COUCHBASE_RBAC_NAME=admin
     - COUCHBASE_RAM_SIZE=2048
     - COUCHBASE_INDEX_RAM_SIZE=512
   hostname: couchbase-server
   container_name: couchbase-server
   working_dir: /opt/couchbase
   stdin_open: true
   tty: true      
   networks:
     example-network:
       ipv4_address: 172.16.238.16
   entrypoint: [""]
   command: sh -c "/opt/couchbase/init/init-cbserver.sh"

 dashboard:
   restart: unless-stopped
   container_name: dashboard
   image: dashboard
   build: ./dashboard
   ports:
     - 5001:5000
   environment:
     - GRAFANA_HOST=http://admin:password@grafana:3000
   volumes:
     - ./config/targets.json:/app/targets.json
   networks:
      example-network:
        ipv4_address: 172.16.238.10
 
 grafana:
   image: grafana/grafana:8.0.1
   restart: unless-stopped
   volumes:
     - ./config/grafana:/var/lib/grafana
   environment:
     GF_INSTALL_PLUGINS: "simpod-json-datasource,marcusolsson-csv-datasource,ae3e-plotly-panel"
     GF_AUTH_ANONYMOUS_ENABLED: "true"
     GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "ae3e-plotly-panel"
     GF_RENDERING_SERVER_URL: http://renderer:8081/render
     GF_RENDERING_CALLBACK_URL: http://grafana:3000/
   ports:
     - 4000:3000
   networks:
      example-network:
        ipv4_address: 172.16.238.11
 
 renderer:
   image: grafana/grafana-image-renderer:latest
   networks:
      example-network:
        ipv4_address: 172.16.238.12
 
 prometheus:
   restart: unless-stopped
   image: prom/prometheus
   volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./config/alert.rules.yml:/etc/prometheus/alert.rules.yml
   networks:
     example-network:
       ipv4_address: 172.16.238.13
        
 exporter:
   restart: unless-stopped
   build: ./exporter
   volumes:
     - ./config/queries.json:/app/queries.json
   networks:
     example-network:
       ipv4_address: 172.16.238.14
        
 alertmanager:
   restart: unless-stopped
   image: prom/alertmanager
   ports:
     - 9093:9093
   volumes:
     - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
     - ./config/alert_templates:/etc/alertmanager/templates
   networks:
     example-network:
       ipv4_address: 172.16.238.15
       
networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24