global:
  resolve_timeout: 1m
  smtp_from: qa@hcbu.com
  smtp_smarthost: 172.16.238.37:1080

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: "infra-email"

receivers:
  - name: "infra-email"
    email_configs:
      - to: tarun@hcbu.com
        from: notify@hcbu.com
        smarthost: 172.16.238.37:1080


